### ISSUE TITLE
Issue: Optimize and Improve `Reaction` Class Implementation

### ISSUE THREAD

**Issue by csmangum** [Dooders/Pyology#27]
### **Issue: Optimize and Improve `Reaction` Class Implementation**

**Description:**
The `Reaction` class models biochemical reactions but requires improvements for better performance, readability, and error handling. This issue aims to address existing inefficiencies, add missing functionality, and refactor the code for better maintainability.

### **Tasks:**

- [x] **1. Fix `perform_reaction` Function**
    - **Problem:** The current function takes a `metabolites` dictionary but the `Reaction` class expects an `organelle` object with methods like `get_metabolite_quantity`.
    - **Solution:** Modify the function to accept an `organelle` object instead.
    - **Example:**
        ```python
        def perform_reaction(organelle, reaction: Reaction, **kwargs) -> bool:
            """
            Executes the reaction on the given organelle.

            Args:
                organelle: Object with methods to manage metabolites.
                reaction (Reaction): The reaction to perform.
                **kwargs: Additional keyword arguments for reaction execution.

            Returns:
                bool: True if the reaction succeeded, False otherwise.
            """
            try:
                reaction.execute(organelle, **kwargs)
                return True
            except ReactionError:
                return False
        ```

- [x] **2. Add Type Hints and Docstrings**
    - **Problem:** Code readability is hampered due to missing type annotations and explanations.
    - **Solution:** Add type hints and docstrings for all methods.
    - **Example:**
        ```python
        def execute(
            self, organelle: Any, time_step: float = 1.0, use_rates: bool = False
        ) -> float:
            """
            Executes the reaction.

            Args:
                organelle: Object representing the environment for the reaction.
                time_step (float): Duration of the reaction step.
                use_rates (bool): Whether to apply enzyme kinetics.

            Returns:
                float: The rate at which the reaction proceeded.
            """
            # Method implementation...
        ```

- [x] **3. Implement Reversible Reactions**
    - **Problem:** The `reversible` parameter is not utilized, limiting the reaction's flexibility.
    - **Solution:** Adjust the `execute` method to support reversible reactions.
    - **Example:**
        ```python
        def execute(self, organelle, reverse: bool = False, **kwargs):
            if self.reversible and reverse:
                substrates, products = self.products, self.substrates
            else:
                substrates, products = self.substrates, self.products

            # Proceed with reaction using substrates and products.
        ```

- [x] **4. Improve Error Handling**
    - **Problem:** Errors like insufficient substrates could be handled more gracefully.
    - **Solution:** Provide more detailed error messages and catch exceptions.
    - **Example:**
        ```python
        try:
            result = self._execute_without_rates(organelle, time_step)
            if result == 0:
                raise ReactionError(f"Reaction '{self.name}' could not proceed due to insufficient substrates.")
        except ReactionError as e:
            logger.error(f"Error during '{self.name}' execution: {e}")
            raise
        ```

- [x] **5. Optimize Metabolite Handling**
    - **Problem:** Substrate quantities are looked up multiple times, impacting performance.
    - **Solution:** Cache the quantities to reduce redundant calculations.
    - **Example:**
        ```python
        substrate_quantities = {met: organelle.get_metabolite_quantity(met) for met in self.substrates}
        reaction_rate = min(substrate_quantities[met] / amount for met, amount in self.substrates.items())
        ```

- [x] **6. Refactor Logging**
    - **Problem:** Logging is verbose and can be improved for clarity.
    - **Solution:** Use helper methods for repeated logging.
    - **Example:**
        ```python
        def _log_substrate_usage(self, substrates: Dict[str, float], rate: float):
            for met, amount in substrates.items():
                logger.debug(f"Using {amount * rate} of {met} for reaction '{self.name}'.")
        ```

- [x] **7. Validate Enzyme Object on Initialization**
    - **Problem:** The `Reaction` class assumes the `enzyme` object has specific methods.
    - **Solution:** Add validation to ensure the enzyme meets requirements.
    - **Example:**
        ```python
        def __post_init__(self):
            if not hasattr(self.enzyme, 'calculate_rate'):
                raise AttributeError("Enzyme must have a 'calculate_rate' method.")
        ```

- [x] **8. Improve Code Readability**
    - **Problem:** Code could be more readable with better variable names and formatting.
    - **Solution:** Rename variables and format code according to PEP 8.
    - **Example:**
        ```python
        for substrate, required_amount in self.substrates.items():
            available_amount = organelle.get_metabolite_quantity(substrate)
            if available_amount < required_amount:
                logger.error(f"Insufficient {substrate}: Needed {required_amount}, Available {available_amount}.")
                return False
        ```

- [x] **9. Add Unit Tests**
    - **Problem:** The current implementation lacks tests, making it hard to verify changes.
    - **Solution:** Write unit tests to verify functionality.
    - **Example:**
        ```python
        def test_can_react_with_sufficient_substrates():
            organelle = MockOrganelle({'ATP': 10, 'NADH': 5})
            reaction = Reaction('ATPase', enzyme, {'ATP': 2}, {'ADP': 2})
            assert reaction.can_react(organelle) is True

        def test_execute_fails_with_insufficient_substrates():
            organelle = MockOrganelle({'ATP': 1})
            reaction = Reaction('ATPase', enzyme, {'ATP': 2}, {'ADP': 2})
            with pytest.raises(ReactionError):
                reaction.execute(organelle)
        ```

- [x] **10. Remove Unused Imports**
    - **Problem:** The import `TYPE_CHECKING` is not used, which adds unnecessary clutter.
    - **Solution:** Remove unused imports.
    - **Example:** Remove `TYPE_CHECKING` if no conditional imports are required:
        ```python
        # Remove this line if not needed
        # from typing import TYPE_CHECKING
        ```

- [x] **11. Enhance Documentation**
    - **Problem:** There is no clear guide on how to use the `Reaction` class.
    - **Solution:** Add examples in the README or in the docstrings.
    - **Example:**
        ```markdown
        ## Using the Reaction Class
        ```python
        enzyme = Enzyme(k_m=0.5, vmax=1.0)
        reaction = Reaction('Glycolysis', enzyme, {'Glucose': 1}, {'Pyruvate': 2}, reversible=True)
        organelle = Organelle()
        
        # Check if the reaction can proceed
        if reaction.can_react(organelle):
            reaction.execute(organelle)
        ```
        ```

---

### **Additional Notes:**
- This issue is intended to improve the overall quality and functionality of the `Reaction` class.
- Feel free to adjust or break down tasks further if needed.
- Reach out for any clarifications or guidance on specific tasks.
