### ISSUE TITLE
Issue: Enhance `Enzyme` Class to Model Signal Transduction Cascades and Feedback Loops

### ISSUE THREAD

**Issue by csmangum** [Dooders/Pyology#32]
# Issue: Enhance `Enzyme` Class to Model Signal Transduction Cascades and Feedback Loops

## Summary

The current `Enzyme` class lacks the capability to accurately model signal transduction pathways, especially concerning activation cascades and feedback loops. To make the class more realistic and accurate for biochemical simulations, we propose a series of enhancements that will allow it to:

- Represent activation states and participate in cascades.
- Incorporate positive and negative feedback mechanisms.
- Improve kinetic modeling with advanced catalytic processes.
- Simulate time-dependent changes in enzyme activities and metabolite concentrations.

### 1. Implement Activation States and Cascades

- **Activation State**: Introduce an `active` attribute to represent whether the enzyme is active or inactive.
- **Activation Methods**: Add `activate()` and `deactivate()` methods to manage the enzyme's state.
- **Cascades**: Allow enzymes to activate or deactivate other enzymes via a `regulate_enzyme()` method, simulating cascade effects.
- **Downstream Enzymes**: Include a `downstream_enzymes` list to hold enzymes that are regulated by the current enzyme.

### 2. Incorporate Feedback Mechanisms

- **Feedback in `calculate_rate()`**: Modify the method to account for feedback from downstream metabolites or products.
- **Positive and Negative Feedback**: Implement mechanisms where metabolite concentrations can enhance or inhibit enzyme activity.

### 3. Enhance the Catalytic Process

- **`catalyze()` Method**: Define a method that updates metabolite concentrations over time, considering the reaction's stoichiometry.
- **Multiple Substrates and Products**: Extend support for reactions involving multiple substrates and products.

### 4. Improve Kinetic Modeling

- **Inhibition Types**: Refine inhibition modeling to include competitive and non-competitive inhibition.
- **Cooperative Binding**: Introduce cooperative effects using models like the Hill equation for more complex kinetics.

### 5. Add Time Dynamics

- **Time-Dependent Simulations**: Incorporate a time step `dt` in the `catalyze()` method to simulate dynamic changes over time.

## Proposed Implementation

Here is the updated `Enzyme` class incorporating the proposed enhancements:

```python
from typing import Dict, List, Optional

from .metabolite import Metabolite


class Enzyme:
    """
    Represents an enzyme that can catalyze reactions and participate in signal transduction pathways.

    Parameters
    ----------
    name : str
        The name of the enzyme.
    k_cat : float
        The catalytic constant (turnover number) of the enzyme.
    k_m : Dict[str, float]
        The Michaelis constants for multiple substrates.
    inhibitors : Dict[str, float], optional
        The inhibition constants for multiple inhibitors.
    activators : Dict[str, float], optional
        The activation constants for multiple activators.
    active : bool, optional
        The current activation state of the enzyme. Defaults to True.
    downstream_enzymes : List['Enzyme'], optional
        Enzymes that are activated or deactivated by this enzyme.

    Methods
    -------
    activate()
        Activates the enzyme.
    deactivate()
        Deactivates the enzyme.
    regulate_enzyme(target_enzyme: 'Enzyme', action: str)
        Activates or deactivates a target enzyme.
    calculate_rate(metabolites: Dict[str, Metabolite]) -> float
        Calculates the rate of the reaction catalyzed by the enzyme.
    catalyze(metabolites: Dict[str, Metabolite], dt: float)
        Simulates the catalysis over a time step dt.
    """

    def __init__(
        self,
        name: str,
        k_cat: float,
        k_m: Dict[str, float],
        inhibitors: Optional[Dict[str, float]] = None,
        activators: Optional[Dict[str, float]] = None,
        active: bool = True,
        downstream_enzymes: Optional[List['Enzyme']] = None,
    ):
        self.name = name
        self.k_cat = k_cat
        self.k_m = k_m
        self.inhibitors = inhibitors or {}
        self.activators = activators or {}
        self.active = active
        self.downstream_enzymes = downstream_enzymes or []

    def activate(self):
        """Activates the enzyme."""
        self.active = True

    def deactivate(self):
        """Deactivates the enzyme."""
        self.active = False

    def regulate_enzyme(self, target_enzyme: 'Enzyme', action: str):
        """
        Activates or deactivates a target enzyme.

        Parameters
        ----------
        target_enzyme : Enzyme
            The enzyme to regulate.
        action : str
            The action to perform ('activate' or 'deactivate').
        """
        if action == 'activate':
            target_enzyme.activate()
        elif action == 'deactivate':
            target_enzyme.deactivate()

    def calculate_rate(self, metabolites: Dict[str, Metabolite]) -> float:
        if not self.active:
            return 0.0  # Inactive enzymes do not catalyze reactions

        rate = self.k_cat

        # Michaelis-Menten kinetics
        for substrate, k_m in self.k_m.items():
            metabolite = metabolites.get(substrate)
            if metabolite is None:
                return 0.0  # Required substrate is missing
            conc = metabolite.quantity
            rate *= conc / (k_m + conc)

        # Inhibition effects
        for inhibitor, k_i in self.inhibitors.items():
            metabolite = metabolites.get(inhibitor)
            if metabolite:
                conc = metabolite.quantity
                rate /= (1 + conc / k_i)

        # Activation effects
        for activator, k_a in self.activators.items():
            metabolite = metabolites.get(activator)
            if metabolite:
                conc = metabolite.quantity
                rate *= (1 + conc / k_a)

        # Feedback regulation (example for negative feedback)
        # You can customize this section based on specific feedback mechanisms
        # Example: Product inhibition
        # for product_name in self.products:
        #     product = metabolites.get(product_name)
        #     if product:
        #         conc = product.quantity
        #         rate /= (1 + conc / feedback_constant)

        return rate

    def catalyze(self, metabolites: Dict[str, Metabolite], dt: float):
        """
        Simulates the catalysis over a time step dt.

        Parameters
        ----------
        metabolites : Dict[str, Metabolite]
            The metabolites involved in the reaction.
        dt : float
            The time step for the simulation.
        """
        rate = self.calculate_rate(metabolites)
        if rate == 0.0:
            return  # No reaction occurs

        # Update metabolite concentrations
        # Assuming a simple reaction: Substrate -> Product
        # Modify this section based on the actual reaction stoichiometry
        substrates = list(self.k_m.keys())
        if not substrates:
            return

        # For simplicity, assume one substrate and one product
        substrate_name = substrates[0]
        substrate = metabolites.get(substrate_name)
        product_name = f"{substrate_name}_product"  # Define how to get product name
        product = metabolites.get(product_name)

        delta = rate * dt
        substrate.quantity = max(substrate.quantity - delta, 0.0)
        if product:
            product.quantity += delta
        else:
            # Create new product if it doesn't exist
            metabolites[product_name] = Metabolite(name=product_name, quantity=delta)

        # Trigger downstream enzymes in the cascade
        for enzyme in self.downstream_enzymes:
            self.regulate_enzyme(enzyme, 'activate')
```

### Stoichiometry

- **Multiple Substrates and Products**: Modify the `catalyze()` method to handle reactions with multiple substrates and products.
- **Stoichiometric Coefficients**: Use coefficients to accurately update metabolite quantities based on reaction stoichiometry.

### Advanced Kinetics

- **Inhibition Types**: Implement different inhibition models such as competitive and non-competitive inhibition by adjusting rate equations.
- **Cooperative Binding**: Use the Hill equation to model cooperative binding effects:
  ```python
  # Example for cooperative binding
  n = 2  # Hill coefficient
  conc = metabolite.quantity
  rate *= conc**n / (k_m + conc**n)
  ```

### Simulation Framework

- **Time Steps**: Incorporate a simulation loop that updates enzyme states and metabolite concentrations over discrete time steps.
- **Example Simulation Loop**:
  ```python
  def simulate_pathway(enzymes: List[Enzyme], metabolites: Dict[str, Metabolite], total_time: float, dt: float):
      time = 0.0
      while time < total_time:
          for enzyme in enzymes:
              enzyme.catalyze(metabolites, dt)
          time += dt
  ```

### Error Handling

- **Negative Quantities**: Add checks to prevent metabolite quantities from becoming negative.
- **Missing Metabolites**: Handle cases where required substrates or products are missing gracefully.

## Example Usage

Here's an example of how the enhanced `Enzyme` class can be used in a simulation:

```python
from .enzyme import Enzyme
from .metabolite import Metabolite

# Define metabolites
metabolites = {
    'A': Metabolite(name='A', quantity=100.0),
    'B': Metabolite(name='B', quantity=0.0),
    'C': Metabolite(name='C', quantity=0.0),
}

# Define enzymes
enzyme1 = Enzyme(
    name='Enzyme1',
    k_cat=1.0,
    k_m={'A': 10.0},
    downstream_enzymes=[],
)

enzyme2 = Enzyme(
    name='Enzyme2',
    k_cat=1.0,
    k_m={'B': 10.0},
    active=False,  # Initially inactive
    downstream_enzymes=[],
)

# Enzyme1 activates Enzyme2
enzyme1.downstream_enzymes.append(enzyme2)

# List of enzymes in the pathway
enzymes = [enzyme1, enzyme2]

# Simulate the pathway
def simulate_pathway(enzymes, metabolites, total_time, dt):
    time = 0.0
    while time < total_time:
        for enzyme in enzymes:
            enzyme.catalyze(metabolites, dt)
        time += dt

simulate_pathway(enzymes, metabolites, total_time=100.0, dt=1.0)
```

## Benefits

By implementing these enhancements, the `Enzyme` class will be more capable of:

- Simulating complex biochemical pathways with activation cascades.
- Modeling feedback loops that are essential in biological regulation.
- Providing a foundation for dynamic simulations of metabolite concentrations over time.

## References

- **Michaelis-Menten Kinetics**: [Wikipedia](https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics)
- **Hill Equation**: [Wikipedia](https://en.wikipedia.org/wiki/Hill_equation_(biochemistry))
- **Signal Transduction Pathways**: [Alberts et al., Molecular Biology of the Cell](https://www.ncbi.nlm.nih.gov/books/NBK26822/)

## Tasks

- [x] Update the `Enzyme` class with the proposed enhancements.
- [x] Modify existing unit tests or write new ones to cover the new functionality.
- [x] Update documentation to reflect changes.
- [x] Perform simulations to validate the enhanced model.

---

**Note**: Please adjust the code and examples as needed to fit the specific context and requirements of your project.: Enhance `Enzyme` Class to Model Signal Transduction Cascades and Feedback Loops

## Summary

The current `Enzyme` class lacks the capability to accurately model signal transduction pathways, especially concerning activation cascades and feedback loops. To make the class more realistic and accurate for biochemical simulations, we propose a series of enhancements that will allow it to:

- Represent activation states and participate in cascades.
- Incorporate positive and negative feedback mechanisms.
- Improve kinetic modeling with advanced catalytic processes.
- Simulate time-dependent changes in enzyme activities and metabolite concentrations.

### 1. Implement Activation States and Cascades

- **Activation State**: Introduce an `active` attribute to represent whether the enzyme is active or inactive.
- **Activation Methods**: Add `activate()` and `deactivate()` methods to manage the enzyme's state.
- **Cascades**: Allow enzymes to activate or deactivate other enzymes via a `regulate_enzyme()` method, simulating cascade effects.
- **Downstream Enzymes**: Include a `downstream_enzymes` list to hold enzymes that are regulated by the current enzyme.

### 2. Incorporate Feedback Mechanisms

- **Feedback in `calculate_rate()`**: Modify the method to account for feedback from downstream metabolites or products.
- **Positive and Negative Feedback**: Implement mechanisms where metabolite concentrations can enhance or inhibit enzyme activity.

### 3. Enhance the Catalytic Process

- **`catalyze()` Method**: Define a method that updates metabolite concentrations over time, considering the reaction's stoichiometry.
- **Multiple Substrates and Products**: Extend support for reactions involving multiple substrates and products.

### 4. Improve Kinetic Modeling

- **Inhibition Types**: Refine inhibition modeling to include competitive and non-competitive inhibition.
- **Cooperative Binding**: Introduce cooperative effects using models like the Hill equation for more complex kinetics.

### 5. Add Time Dynamics

- **Time-Dependent Simulations**: Incorporate a time step `dt` in the `catalyze()` method to simulate dynamic changes over time.

## Proposed Implementation

Here is the updated `Enzyme` class incorporating the proposed enhancements:

```python
from typing import Dict, List, Optional

from .metabolite import Metabolite


class Enzyme:
    """
    Represents an enzyme that can catalyze reactions and participate in signal transduction pathways.

    Parameters
    ----------
    name : str
        The name of the enzyme.
    k_cat : float
        The catalytic constant (turnover number) of the enzyme.
    k_m : Dict[str, float]
        The Michaelis constants for multiple substrates.
    inhibitors : Dict[str, float], optional
        The inhibition constants for multiple inhibitors.
    activators : Dict[str, float], optional
        The activation constants for multiple activators.
    active : bool, optional
        The current activation state of the enzyme. Defaults to True.
    downstream_enzymes : List['Enzyme'], optional
        Enzymes that are activated or deactivated by this enzyme.

    Methods
    -------
    activate()
        Activates the enzyme.
    deactivate()
        Deactivates the enzyme.
    regulate_enzyme(target_enzyme: 'Enzyme', action: str)
        Activates or deactivates a target enzyme.
    calculate_rate(metabolites: Dict[str, Metabolite]) -> float
        Calculates the rate of the reaction catalyzed by the enzyme.
    catalyze(metabolites: Dict[str, Metabolite], dt: float)
        Simulates the catalysis over a time step dt.
    """

    def __init__(
        self,
        name: str,
        k_cat: float,
        k_m: Dict[str, float],
        inhibitors: Optional[Dict[str, float]] = None,
        activators: Optional[Dict[str, float]] = None,
        active: bool = True,
        downstream_enzymes: Optional[List['Enzyme']] = None,
    ):
        self.name = name
        self.k_cat = k_cat
        self.k_m = k_m
        self.inhibitors = inhibitors or {}
        self.activators = activators or {}
        self.active = active
        self.downstream_enzymes = downstream_enzymes or []

    def activate(self):
        """Activates the enzyme."""
        self.active = True

    def deactivate(self):
        """Deactivates the enzyme."""
        self.active = False

    def regulate_enzyme(self, target_enzyme: 'Enzyme', action: str):
        """
        Activates or deactivates a target enzyme.

        Parameters
        ----------
        target_enzyme : Enzyme
            The enzyme to regulate.
        action : str
            The action to perform ('activate' or 'deactivate').
        """
        if action == 'activate':
            target_enzyme.activate()
        elif action == 'deactivate':
            target_enzyme.deactivate()

    def calculate_rate(self, metabolites: Dict[str, Metabolite]) -> float:
        if not self.active:
            return 0.0  # Inactive enzymes do not catalyze reactions

        rate = self.k_cat

        # Michaelis-Menten kinetics
        for substrate, k_m in self.k_m.items():
            metabolite = metabolites.get(substrate)
            if metabolite is None:
                return 0.0  # Required substrate is missing
            conc = metabolite.quantity
            rate *= conc / (k_m + conc)

        # Inhibition effects
        for inhibitor, k_i in self.inhibitors.items():
            metabolite = metabolites.get(inhibitor)
            if metabolite:
                conc = metabolite.quantity
                rate /= (1 + conc / k_i)

        # Activation effects
        for activator, k_a in self.activators.items():
            metabolite = metabolites.get(activator)
            if metabolite:
                conc = metabolite.quantity
                rate *= (1 + conc / k_a)

        # Feedback regulation (example for negative feedback)
        # You can customize this section based on specific feedback mechanisms
        # Example: Product inhibition
        # for product_name in self.products:
        #     product = metabolites.get(product_name)
        #     if product:
        #         conc = product.quantity
        #         rate /= (1 + conc / feedback_constant)

        return rate

    def catalyze(self, metabolites: Dict[str, Metabolite], dt: float):
        """
        Simulates the catalysis over a time step dt.

        Parameters
        ----------
        metabolites : Dict[str, Metabolite]
            The metabolites involved in the reaction.
        dt : float
            The time step for the simulation.
        """
        rate = self.calculate_rate(metabolites)
        if rate == 0.0:
            return  # No reaction occurs

        # Update metabolite concentrations
        # Assuming a simple reaction: Substrate -> Product
        # Modify this section based on the actual reaction stoichiometry
        substrates = list(self.k_m.keys())
        if not substrates:
            return

        # For simplicity, assume one substrate and one product
        substrate_name = substrates[0]
        substrate = metabolites.get(substrate_name)
        product_name = f"{substrate_name}_product"  # Define how to get product name
        product = metabolites.get(product_name)

        delta = rate * dt
        substrate.quantity = max(substrate.quantity - delta, 0.0)
        if product:
            product.quantity += delta
        else:
            # Create new product if it doesn't exist
            metabolites[product_name] = Metabolite(name=product_name, quantity=delta)

        # Trigger downstream enzymes in the cascade
        for enzyme in self.downstream_enzymes:
            self.regulate_enzyme(enzyme, 'activate')
```

### Stoichiometry

- **Multiple Substrates and Products**: Modify the `catalyze()` method to handle reactions with multiple substrates and products.
- **Stoichiometric Coefficients**: Use coefficients to accurately update metabolite quantities based on reaction stoichiometry.

### Advanced Kinetics

- **Inhibition Types**: Implement different inhibition models such as competitive and non-competitive inhibition by adjusting rate equations.
- **Cooperative Binding**: Use the Hill equation to model cooperative binding effects:
  ```python
  # Example for cooperative binding
  n = 2  # Hill coefficient
  conc = metabolite.quantity
  rate *= conc**n / (k_m + conc**n)
  ```

### Simulation Framework

- **Time Steps**: Incorporate a simulation loop that updates enzyme states and metabolite concentrations over discrete time steps.
- **Example Simulation Loop**:
  ```python
  def simulate_pathway(enzymes: List[Enzyme], metabolites: Dict[str, Metabolite], total_time: float, dt: float):
      time = 0.0
      while time < total_time:
          for enzyme in enzymes:
              enzyme.catalyze(metabolites, dt)
          time += dt
  ```

### Error Handling

- **Negative Quantities**: Add checks to prevent metabolite quantities from becoming negative.
- **Missing Metabolites**: Handle cases where required substrates or products are missing gracefully.

## Example Usage

Here's an example of how the enhanced `Enzyme` class can be used in a simulation:

```python
from .enzyme import Enzyme
from .metabolite import Metabolite

# Define metabolites
metabolites = {
    'A': Metabolite(name='A', quantity=100.0),
    'B': Metabolite(name='B', quantity=0.0),
    'C': Metabolite(name='C', quantity=0.0),
}

# Define enzymes
enzyme1 = Enzyme(
    name='Enzyme1',
    k_cat=1.0,
    k_m={'A': 10.0},
    downstream_enzymes=[],
)

enzyme2 = Enzyme(
    name='Enzyme2',
    k_cat=1.0,
    k_m={'B': 10.0},
    active=False,  # Initially inactive
    downstream_enzymes=[],
)

# Enzyme1 activates Enzyme2
enzyme1.downstream_enzymes.append(enzyme2)

# List of enzymes in the pathway
enzymes = [enzyme1, enzyme2]

# Simulate the pathway
def simulate_pathway(enzymes, metabolites, total_time, dt):
    time = 0.0
    while time < total_time:
        for enzyme in enzymes:
            enzyme.catalyze(metabolites, dt)
        time += dt

simulate_pathway(enzymes, metabolites, total_time=100.0, dt=1.0)
```

## Benefits

By implementing these enhancements, the `Enzyme` class will be more capable of:

- Simulating complex biochemical pathways with activation cascades.
- Modeling feedback loops that are essential in biological regulation.
- Providing a foundation for dynamic simulations of metabolite concentrations over time.

## References

- **Michaelis-Menten Kinetics**: [Wikipedia](https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics)
- **Hill Equation**: [Wikipedia](https://en.wikipedia.org/wiki/Hill_equation_(biochemistry))
- **Signal Transduction Pathways**: [Alberts et al., Molecular Biology of the Cell](https://www.ncbi.nlm.nih.gov/books/NBK26822/)

## Tasks

- [ ] Update the `Enzyme` class with the proposed enhancements.
- [ ] Modify existing unit tests or write new ones to cover the new functionality.
- [ ] Update documentation to reflect changes.
- [ ] Perform simulations to validate the enhanced model.
